[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "app/static/SpaceGrotesk-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "SpaceGroteskHeader"
url = "app/static/SpaceGrotesk-SemiBold.ttf"

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-BoldItalic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Italic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Regular.ttf"
style = "normal"
weight = 400

[theme]
primaryColor = "#9B89CF"
backgroundColor = "#F9F7FD"
secondaryBackgroundColor = "#EDE9F6"
textColor = "#4A3F6D"
linkColor = "#9B89CF" # Ajustei para ser igual ao primaryColor para consistência
borderColor = "#D9D1E9"
showWidgetBorder = true
baseRadius = "0.6rem"
font = "SpaceGrotesk"
headingFont = "SpaceGroteskHeader"
codeFont = "SpaceMono"
codeBackgroundColor = "#EDE9F6"
showSidebarBorder = true
baseFontSize=24

[theme.sidebar]
backgroundColor = "#EDE9F6"
secondaryBackgroundColor = "#D9D1E9"